name: Code coverage test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CARGO_TARGET_DIR: "/var/tmp/.cargo-target"
      X_CI_PROFILE_DIRECTORY: "/var/tmp/.profraw"

    steps:
    - uses: actions/checkout@v3

    - name: install extra packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lighttpd

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: llvm-tools

    - name: build grcov
      run: cargo install grcov

    - name: Prepare
      run: make prepare

    - name: Run tests
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Cinstrument-coverage'
        LLVM_PROFILE_FILE: "/var/tmp/.profraw/tests-%p-%m.profraw"
      run: cargo test --no-fail-fast --all-targets --workspace

    - name: build coverage data
      run:
        mkdir -p "${CARGO_TARGET_DIR}/coverage/" &&
        grcov
        "${X_CI_PROFILE_DIRECTORY}"
        --binary-path "${CARGO_TARGET_DIR}/debug"
        --llvm
        --branch
        -s "."
        -o "${CARGO_TARGET_DIR}/coverage/"
        --keep-only '*'
        --ignore "${CARGO_HOME}/**"
        --ignore "${CARGO_TARGET_DIR}/**"
        --ignore-not-existing
        --output-types html,cobertura,lcov
        --commit-sha "${CI_COMMIT_SHA}"
        ${CI_COMMIT_BRANCH:+--vcs-branch "${CI_COMMIT_BRANCH}"}

    - name: Coveralls upload
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: "${{ env.CARGO_TARGET_DIR }}/coverage/lcov"
