name: Generic build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUST_TEST_LOG: debug

jobs:
  build:
    runs-on: ubuntu-latest

    # test 1.84 because this is the rust version in RHEL 8
    strategy:
      matrix:
        toolchain: [ "stable", "nightly", "1.84" ]

    steps:
    - uses: actions/checkout@v3

    - name: install extra packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: lighttpd

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Prepare
      shell: bash
      env:
        CI_TOOLCHAIN: ${{ matrix.toolchain }}
      run: |
        rm -f .local.mk Cargo.lock Cargo.toml .cargo/config
        printf 'RUST%s_COMPAT = t' "${CI_TOOLCHAIN//./}" > .local.mk
        make update-compat

    - name: Run build
      run:
        cargo build --all-targets --locked --tests --benches --workspace --release

    - name: Run tests
      run:
        cargo test

    - name: Upload Cargo.lock
      uses: actions/upload-artifact@v4
      if: ${{ matrix.toolchain  == 'stable' }}
      with:
        name: Cargo.lock
        path: Cargo.lock
