name: Generic build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    ## rust 1.62 is tested because it is the version in RHEL 8; it
    ## requires extra setup
    strategy:
      matrix:
        toolchain: [ "stable", "nightly", "1.62" ]

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Prepare
      run: make prepare

    - name: Make rust 'nightly'
      if: ${{ matrix.toolchain }} == '1.62'
      run: export RUSTC_BOOTSTRAP=1

    - name: Run build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
