name: Generic build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    ## rust 1.62 is tested because it is the version in RHEL 8; but
    ## tests requires more recent features so that they are not run
    ## for this version
    strategy:
      matrix:
        toolchain: [ "stable", "nightly", "1.62" ]

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Prepare
      if: ${{ matrix.toolchain != '1.62' }}
      run: make prepare

    - name: Prepare (1.62)
      if: ${{ matrix.toolchain == '1.62' }}
      run: make prepare RUST162_COMPAT=t

    - name: Run build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Run tests
      if: ${{ matrix.toolchain != '1.62' }}
      uses: actions-rs/cargo@v1
      with:
        command: test
